version: '3.8'
services:
  ams_db:
    image: 'postgres:latest'
    container_name: ams_db
    restart: always
    env_file: docker.env
    ports:
      - "5432:5432"


volumes:
  omdb_db:
    driver: local